CREATE TABLE empleado
( cedula	NUMBER(10),
  nombre    	VARCHAR(30) 	NOT NULL,
  jefe	   	NUMBER(10) REFERENCES empleado(cedula),
  salario    	NUMBER(10,2) 	NOT NULL CHECK (salario > 0 ) ,
  comision  	NUMBER(3)	CHECK (comision between 0 and 100),
  cargo      	VARCHAR(20) 	NOT NULL,
  depto      	NUMBER(6)	NOT NULL REFERENCES departamento,
  CONSTRAINT PK_EMPLEADO PRIMARY KEY (CEDULA)
);

CREATE TABLE empleado
( cedula	NUMBER(10),
  nombre    	VARCHAR(30) 	NOT NULL,
  jefe	   	NUMBER(10),
  salario    	NUMBER(10,2) 	NOT NULL CHECK (salario > 0 ) ,
  comision  	NUMBER(3)	CHECK (comision between 0 and 100),
  cargo      	VARCHAR(20) 	NOT NULL,
  depto      	NUMBER(6)	NOT NULL REFERENCES departamento,
  CONSTRAINT PK_EMPLEADO PRIMARY KEY (CEDULA),
  CONSTRAINT FK_EMPLEADO FOREIGN KEY  (JEFE) REFERENCES EMPLEADO(CEDULA)
);


ORA-00001: unique constraint (UMG.PK_EMPLEADO) violated
ORA-02291: integrity constraint (UMG.FK_EMPLEADO) violated - parent key not found



0.00 seconds


ALTER TABLE ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY (CEDULA)

ALTER TABLE ADD CONSTRAINT FK_EMPLEADO_CEDULA (JEFE) REFERENCES EMPLEADO(CEDULA);

	INSERT INTO EMPLEADO VALUES
	(3, 'JOSE DOMINGUEZ', NULL, 3000, 75, 'PROGRAMADOR JUNIOR', 1, 3)

ORA-00913: too many values

INSERT INTO 
(CÃ‰DULA, NOMBRE, JEFE, SALARIO, COMISION, CARGO, DEPTO)
VALUES
(3, 'JOSE DOMINGUEZ', NULL, 3000, 75, 'PROGRAMADOR JUNIOR', 1)

drop table empleado

	ORA-00942: table or view does not exist

	ORA-02291: integrity constraint (UMG.SYS_C007307) violated - parent key not found
	ORA-00001: unique constraint (UMG.SYS_C007306) violated
	
	
	
CREATE TABLE empleado
( cedula	NUMBER(10) 	PRIMARY KEY,
  nombre    	VARCHAR(30) 	NOT NULL,
  jefe	   	NUMBER(10) REFERENCES empleado(cedula),
  salario    	NUMBER(10,2) 	NOT NULL CHECK (salario > 0 ) ,
  comision  	NUMBER(3)	CHECK (comision between 0 and 100),
  cargo      	VARCHAR(20) 	NOT NULL,
  depto      	NUMBER(6)	NOT NULL REFERENCES departamento
);
INSERT INTO EMPLEADO VALUES
(3, 'JOSE DOMINGUEZ', NULL, 3000, 75, 'PROGRAMADOR JUNIOR', 1, 3)


CREATE TABLE empleado
( cedula	NUMBER(10),
  nombre    	VARCHAR(30) 	NOT NULL,
  jefe	   	NUMBER(10),
  salario    	NUMBER(10,2) 	NOT NULL CHECK (salario > 0 ) ,
  comision  	NUMBER(3)	CHECK (comision between 0 and 100),
  cargo      	VARCHAR(20) 	NOT NULL,
  depto      	NUMBER(6)	NOT NULL REFERENCES departamento,
  CONSTRAINT PK_EMPLEADO PRIMARY KEY (CEDULA),
  CONSTRAINT FK_EMPLEADO FOREIGN KEY  (JEFE) REFERENCES EMPLEADO(CEDULA)
);


drop table empleado

SELECT * FROM DEPARTAMENTO

select *  from empleado

INSERT INTO EMPLEADO 
(cedula	, NOMBRE, JEFE, SALARIO, comision, CARGO, DEPTO)
VALUES
(4, 'JOSE DOMINGUEZ', 5, 3000, 75, 'PROGRAMADOR JUNIOR', 1)

	
	
	
	
CREATE TABLE envio (
	snro 	NUMBER(6),
	pnro 	NUMBER(6),
	cantidad NUMBER(6) NOT NULL,
	PRIMARY KEY(snro,pnro)
);

desc envio
	
	
	/*010918*/
	
DROP TABLE ENVIO
CREATE TABLE envio (
	snro 	NUMBER(6),
	pnro 	NUMBER(6),
	cantidad NUMBER(6) NOT NULL
);

DESCRIBE ENVIO

ALTER TABLE ENVIO 
ADD CONSTRAINT PK_ENVIO	PRIMARY KEY(snro,pnro);

ALTER TABLE ENVIO ADD CONSTRAINT FK_ENVIO FOREIGN KEY(snro,pnro) REFERENCES FACTURA (IDFACTURA);

ALTER TABLE ENVIO
ADD COMENTARIO VARCHAR2(100);

ALTER TABLE ENVIO
ADD OBSERVACIONES VARCHAR2(100); /*AGREGAR ATRIBUTOS O CAMPOS*/

ALTER TABLE ENVIO
MODIFY OBSERVACIONES VARCHAR2(400);  /*MODIFICAR CAMPOS*/

ALTER TABLE ENVIO
DROP (OBSERVACIONES); /*ELIMINAR ATRIBUTOS O CAMPOS*/

SELECT * FROM EMPLEADO1

CREATE TABLE empleado1(
cedula 	NUMBER(8) PRIMARY KEY,
nombre 	VARCHAR(25) NOT NULL,
carnet 	NUMBER(5) UNIQUE NOT NULL);


INSERT INTO empleado1 VALUES(10,'Dino',20);
INSERT INTO empleado1 VALUES(20,'Pedro',30);

SELECT * FROM AUTO
CREATE TABLE auto(
placa 	VARCHAR(10) PRIMARY KEY,
marca 	VARCHAR(20) NOT NULL);

INSERT INTO auto VALUES('CTV 40','BMW');
INSERT INTO auto VALUES('CTV 60','BMW');
INSERT INTO auto VALUES('CTV 80','BMW');


SELECT * FROM FACTURA
DROP TABLE FACTURA

CREATE TABLE factura (
codigo NUMBER(6) PRIMARY KEY,
fecha 	  DATE NOT NULL,
cedula NUMBER(8) 	REFERENCES empleado1,
placa 	  VARCHAR(10) 	REFERENCES auto,
CHECK ( (placa IS NULL AND cedula IS NOT NULL)   
         OR 
        (placa IS NOT NULL AND cedula IS NULL)
       	   )
);

SELECT * FROM FACTURA
INSERT INTO factura VALUES(300,SYSDATE,10,NULL);

INSERT INTO factura VALUES(900,TO_DATE('28/12/16','dd/mm/yyyy'),NULL,'CTV 40');
INSERT INTO factura VALUES(901,TO_DATE('28/12/18','dd/mm/yyyy'),NULL,'CTV 40');
				
		propia de Oracle, en el SQL estÃ¡ndar es CAST

Note que las dos siguientes inserciones fallan:

INSERT INTO factura (CODIGO, FECHA, CEDULA, PLACA)
VALUES(500,SYSDATE,10,'CTV 40');

INSERT INTO factura VALUES(600,SYSDATE,NULL,NULL);


DROP TABLE AUTO PURGE
DROP TABLE EMPLEADO1

DROP TABLE FACTURA PURGE;


SELECT * FROM EMPLEADO1
SELECT * FROM AUTO

SELECT F.CODIGO, F.FECHA, F.CEDULA, F.PLACA
FROM FACTURA F
JOIN EMPLEADO1 E ON F.CEDULA = E.CEDULA


SELECT F.CODIGO, F.FECHA, F.CEDULA, F.PLACA, E.NOMBRE, E.CARNET, A.MARCA
FROM FACTURA F, EMPLEADO1 E, AUTO A
WHERE F.CEDULA = E.CEDULA(+)
  AND F.PLACA = A.PLACA (+)
  AND E.CARNET = 20


SELECT * FROM AUTO
UPDATE AUTO SET PLACA = 'CTV 100'
WHERE PLACA = 'CTV 60'

DELETE FROM AUTO 
WHERE PLACA = 'CTV 100'


ALTER TABLE AUTO ADD MOTORX VARCHAR2(100);

ALTER TABLE AUTO RENAME COLUMN MOTORX TO MOTOR

ALTER TABLE AUTO DROP COLUMN MOTOR




	
	
	
	
	
	
	
	
	
	
	
	
	
